# These are supported funding model platforms

github: #[Mx4cjc4f. Dlink777. jcoon2c@gmail.com. jessie_9637@hotmail.com] # Replace with up to 4 GitHub Sponsors-enabled usernames DLINK777. Mx4cjc4f. Androidx. Firebase e.g., [user1, user2]
patreon: skywinder # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi:  # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: ["https://www.paypal.me/panforumliquidity.checkout@V8"]  # Replace with a single custom sponsorship URLko_fi: pandorumliquidity29@gmail.com

